### ISSUE TITLE
Player colors switched upon .sgf generation

### ISSUE THREAD

**Issue by harknus** [DavidEGx/Hive-bga2bs#13]
Exporting e.g., the game https://boardgamearena.com/gamereview?table=119614836
In the game DavidEG plays black and smiechowy plays white.
![image](https://user-images.githubusercontent.com/13743836/97783817-6480ac80-1b9a-11eb-9ce9-ea9cfa584c8b.png)

Exporting the game generates the following code in the exported SGF file:
      P0[id "DavidEG"]
      P1[id "smiechowy"]
which means (without additional sgf tags) that DavidEG plays white and smilechowy plays black.
Opening the .sgf in the Boardspace verify this switch of colors and as such also concludes that the wrong player won: 
![image](https://user-images.githubusercontent.com/13743836/97784051-110f5e00-1b9c-11eb-94d6-9b38a872e659.png)

**Comment by DavidEGx** [comment]
Hopefully fixed in 1b145d11c799f077f59431083e0803473799d1ab.
